IBM/java-sdk-core

build/bintray-config.template
build/sync2MC.sh
pom.xml

This PR adds a `-tests` jar to allow for pulling base test classes and utilities in the Watson service classes. This approach was taken from the [Maven documentation](http://maven.apache.org/guides/mini/guide-attached-tests.html).

Expose tests in library

---

src/main/java/com/ibm/cloud/sdk/core/service/WatsonService.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/BadRequestException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/ConflictException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/ForbiddenException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/InternalServerErrorException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/NotFoundException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/RequestTooLargeException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/ServiceResponseException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/ServiceUnavailableException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/TooManyRequestsException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/UnauthorizedException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/UnsupportedException.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ErrorResponseTest.java

An issue was submitted a while back where users using a certain API couldn't retrieve a `correlation_id` field in their error response due to the way we were handling and wrapping errors. This field was particularly important for support people trying to resolve errors.
This PR changes the main exception class `ServiceResponseException` to handle parsing for error messages, which used to be done in `WatsonService` it also changes what is provided for the user, removing the raw `Response` object in favor of `message` (the parsed error message) and `debuggingInfo`, which is a `Map` of the rest of the response.
A test has been added to validate the debugging information.

Add additional error information

---

src/main/java/com/ibm/cloud/sdk/core/util/RequestUtils.java
src/test/java/com/ibm/cloud/sdk/core/test/util/RequestUtilsTest.java

This PR makes a small change to allow external packages to _just_ grab system information, which currently consists of the Java vendor, Java version OS architecture, OS name, and OS version.
This change is related to a Slack discussion that was had where we decided that by default, the core version would be included in the `User-Agent` header, but that if a `User-Agent` was provided by an external SDK, they could avoid appending the core version.

Add method to just get system info

---

src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java

Related to [this issue](https://github.com/watson-developer-cloud/java-sdk/issues/959).
After some discussion that can be seen in the linked issue, it seems we decided that there are valid use-cases where a service would explicitly return a field with a value of `null`. The change in this PR ensures that those values are not left out of serialization and that users can grab that `null` value in the Java code.

Serialize null values coming back from service APIs

---

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java

A while ago, a change was made to the Java SDK core to try and fix some `SSLHandshakeException`s showing up in Visual Recognition on Oracle JDK 7. The PR to try and make that fix is here: https://github.com/watson-developer-cloud/java-sdk/pull/890
However, there was an issue reported later that this "fix" introduced some other potential problems. Here is that issue: https://github.com/watson-developer-cloud/java-sdk/issues/1020
I went back to investigate by using the old logic and Oracle JDK 7 with Visual Recognition and I didn't run into any problems. Based on the timing of the original occurrence, my guess is it had something to do with the transition to IAM authentication and the new endpoint and was just temporary. Either way, if the original logic works and avoids the potential …

Revert old SSL/TLS logic change

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/main/java/com/ibm/cloud/sdk/core/http/ServiceCall.java
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/main/java/com/ibm/cloud/sdk/core/service/security/IamTokenManager.java
src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java

In [this earlier PR](https://github.com/IBM/java-sdk-core/pull/18), I changed the main GSON instance to always serialize with null values. When testing with the new core, I realized that some API endpoints don't like being sent null values. Originally the change was only made with service responses in mind, so I've tweaked the core logic accordingly. JSON content being sent to the APIs should now behave as before.

Only include nulls in serialization when processing API responses

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/service/exception/ServiceResponseException.java

This PR tweaks the error parsing logic according to [this issue](https://github.ibm.com/Watson/developer-experience/issues/6336).
Additionally, it changes the version of the Guava dependency to work with Java version 1.7, since that's the lowest version we target in the Watson SDK.

Error parsing

---

.travis.yml
src/main/java/com/ibm/cloud/sdk/core/service/security/IamTokenManager.java
src/test/java/com/ibm/cloud/sdk/core/test/service/IamManagerTest.java

Fixes:  https://github.ibm.com/arf/planning-sdk-squad/issues/851

fix: Allow IAM client_id/secret to be supplied for basicauth header

---

.travis.yml
build/generate-index-html.sh
build/push-javadoc-to-gh-pages.sh

This PR pulls from very similar work that was done in the Watson Java SDK to publish the Javadoc on releases. I've already added the site URL to the README, and you can find it to reference here: https://ibm.github.io/java-sdk-core/

Add release docs to GH pages site on releases

---

src/main/java/com/ibm/cloud/sdk/core/service/security/IamOptions.java
src/main/java/com/ibm/cloud/sdk/core/service/security/IamTokenManager.java
src/test/java/com/ibm/cloud/sdk/core/test/service/IamManagerTest.java

This PR fixes the initial changes for issue https://github.ibm.com/arf/planning-sdk-squad/issues/851 :
1. The client id/secret can now be set via the IamOptions class.   This will allow SDK users to configure these values as part of instantiating the generated service object (i.e. the ctor accepts an IamOptions instance).
2. I changed "secret" to be "clientSecret" to be more descriptive and to align with "clientId".
3. The client id/secret values are no longer static.
The actual requirement is to allow SDK users to set the client id/secret values so that interactions with the IAM token server will use an Authorization header that reflects their specific id/secret rather than the default of "bx:bx".

feat(IAM): set client id/secret via IamOptions; corrected terminology

---

src/main/java/com/ibm/cloud/sdk/core/util/ResponseConverterUtils.java
src/main/java/com/ibm/cloud/sdk/core/util/ResponseUtils.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/797 (for Java)
This PR adds the necessary function (and tests) to the Java SDK core to allow us to generate Java code that will support the de-serialization of a top-level (JSON) array within a response body.
With this change, the Java SDK core will support responses which contain an array of JSON object as well as primitive types.
Note that this PR will be a prereq to some related changes in the SDK generator.  That PR will be finished soon.

feat: add de-serialization logic for JSON arrays within response body

---

build/push-javadoc-to-gh-pages.sh

I promise this is the **last** tweak I'll need to make to get the docs generated automatically. They went out mostly fine on the last release except that the main `index.html` file was cleared because I called the script to generate it in the wrong location.
This PR solves that problem and I made sure to test locally, so we should be good now.

Fix generation on docs index page

---

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/service/BaseServiceTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/859
This PR allows a Java SDK to be more easily modify the configuration of the `OkHttpClient` instance used by the Java core for REST API invocations.   With these changes, an SDK user would also have the ability to create and set their own `OkHttpClient` instance for use by the SDK (similar to the Go core).
The new tests added to the BaseServiceTest class should demonstrate the gist of these changes.

feat(http): improve SDK's ability to configure http client instances

---

src/main/java/com/ibm/cloud/sdk/core/http/Response.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

The `Response` class is usually only generated for a successful response (i.e. `200` <= status code < `400`), but there may still be useful information encapsulated in the successful status code. For example, when creating resources `201` and `202` convey different information about what has happened on the server (`Created` vs `Accepted`).
This PR adds a `com.ibm.cloud.sdk.core.http.Response#getStatusCode` method so that additional information of the status code can be accessed by the caller.
It adds a single test `com.ibm.cloud.sdk.core.test.service.ResponseTest#testResponseCode` to demonstrate that the code is set and retrievable.

Added HTTP status code to response

---

src/main/java/com/ibm/cloud/sdk/core/security/icp4d/ICP4DAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/icp4d/ICP4DConfig.java
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/main/java/com/ibm/cloud/sdk/core/service/security/IamOptions.java
src/test/java/com/ibm/cloud/sdk/core/test/service/AuthenticationTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/904
BREAKING CHANGE:
This PR removes support for the standalone "apikey" authentication path
in the BaseService class, including the removal of "setApiKey()".
Going forward, authentication should be configured on a service instance
using generated service ctors or the BaseService.setAuthenticator() method.

feat(*): remove obsolete methods from BaseService

---

src/main/java/com/ibm/cloud/sdk/core/util/DynamicModelTypeAdapterFactory.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java
src/test/java/com/ibm/cloud/sdk/core/test/model/generated/ModelAPProtectedCtor.java

This PR will allow dynamic models (subclasses of DynamicModel<T>) to define a protected (or private) default ctor instead of a public one.   We need this to accommodate the code pattern used by our new oneOf/anyOf processing whereby the parent schema (the schema containing the oneOf/anyOf list) will define a protected default ctor to prevent users from instantiating it (they would have to use a base class instead).   For this reason, we need the DynamicModelTypeAdapterFactory class to recognize a non-public default ctor when checking to see if it should handle a specific class.

feat(serialization): Allow dynamic models to have non-public default ctors

---

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java
src/main/java/com/ibm/cloud/sdk/core/http/HttpConfigOptions.java
src/test/java/com/ibm/cloud/sdk/core/test/http/HttpConfigTest.java

This PR contains the same changes introduced [here](https://github.com/IBM/java-sdk-core/pull/45), just for version `4.x.x`, since I plan to incorporate this change into the Watson Java SDK.

(v4) Allow for proxy auth configuration

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/util/ByteArrayTypeAdapter.java
src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java
src/test/java/com/ibm/cloud/sdk/core/test/util/ByteArrayTypeAdapterTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/908
This PR introduces a Gson Type Adapter for "byte []" values.
This will ensure that any model class fields of type "byte[]" are serialized and deserialized properly.
In the case of "byte[]" this means that the sequence of bytes is transformed into a string of base64-encoded characters.   On the deserialization side, we would transform the string of base64-encoded characters found in the JSON instance by decoding them into their original byte values and store in the resulting byte[].

feat(serialization): added gson type adapter for byte[]

---

src/main/java/com/ibm/cloud/sdk/core/util/DynamicModelTypeAdapterFactory.java
src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java
src/main/java/com/ibm/cloud/sdk/core/util/MapValueObjectTypeAdapter.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/951
This PR introduces changes to avoid ser/deser asymmetry problems when dealing with 
DynamicModels with "Object" as the map value type.
Summary of changes:
1) Introduced new "MapValueObjectTypeAdapter" which will be used specifically for map values when
the map value type is Object.   This is an adaptation of Gson's ObjectTypeAdapter, with the main change being that a JSON number will be deserialized into an instance of Gson's LazilyParseNumber instead of java.lang.Double.
2) DynamicModelTypeAdapterFactory was changed to use MapValueObjectTypeAdapter when the map value type is Object.
3) The relevant testcase was modified to NOT compensate for the unnecessary decimal points when serializing a previously deserialized object, …

feat(serialization): Avoid ser/deser roundtripping asymmetry for Object map value type

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/960
This PR removes the call to `serializeNulls()` when creating a `Gson` instance while serializing JSON content inside `RequestBuilder.bodyContent(String, Object, Object, InputStream)`.
This will ensure that we're serializing JSON body content in the same way no matter whether the operation accepts only JSON content, or JSON content in addition to other types as well.

fix: do not use 'serializeNulls' when initializing Gson

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/service/AuthenticationTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ErrorResponseTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/HeadersTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1011
This PR contains the necessary changes in the Java core to support the new "paramterized URL" feature in the Java generator.
Summary:
1) The BaseService.endPoint field renamed to serviceURL.
2) Added getServiceURL/setServiceURL methods.
3) Deprecated getEndPoint/setEndPoint
4) Added validation of the base URL value to RequestBuilder.constructHttpUrl()
5) Updated tests as needed.

feat: defer validation of serviceURL until first use

---

src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java

Related to https://github.ibm.com/Watson/developer-experience/issues/7520
This PR changes the order in which we search for external credential files, moving the search for a file in the current working directory up just after the user-defined path.

Change order of files checked for authentication

---

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java

Related to https://github.ibm.com/Watson/developer-experience/issues/7541
This PR adds custom warnings for cases when we run into an `SSLHandshakeException`. This could happen for users calling service endpoint on ICP or CP4D because they haven't set up self-signed certificates.

Give more information about SSL handshake exception for ICP/CP4D

---

src/main/java/com/ibm/cloud/sdk/core/service/model/FileWithMetadata.java
src/test/java/com/ibm/cloud/sdk/core/test/service/BaseServiceTest.java

Fixed a few javadoc warnings and fixed a bizarre timing-related issue in a unit test by changing it to use TestNG.

fix: fix javadoc warnings

---

pom.xml

Related to https://github.com/watson-developer-cloud/java-sdk/issues/1095
We got an issue in the Watson Java SDK saying that there were some unwanted dependencies that were irrelevant to the consuming developer and in one case caused a bug in Android with a duplicate dependency.
I went through and removed a couple libraries that we didn't seem to be using in our build process anywhere and set one of the mocking libraries to a test dependency so that it doesn't clutter dependencies down the line.

Remove unused dependencies and set test scope where necessary

---

.gitignore
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java
src/test/java/com/ibm/cloud/sdk/core/test/service/AuthenticationTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ConfigureServiceTest.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
src/test/resources/vcap_services.json

ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1098
The vcap changes were based on @padamstx initial implementation in the service-factory branch. Thanks Phil!
Changes:
- removed the call to the ``configureService()`` method out of the constructor.
- updated the unit tests that were dependent on ``configureService()`` being called when instantiating the BaseService.
- updated how external configuration is loaded from a vcap file based on this [design](https://github.ibm.com/CloudEngineering/openapi-sdkgen/wiki/Design-Of-Service-Config-Changes]). Specifically, the parsing now checks for a matching service name within an entry, if it doesn't find any then it will return the first entry with a matching outer key to the service name.
- other general cleanup of unused code

feat: enhancing vcap parsing & removing configureService reference from BaseService ctor

---

src/main/java/com/ibm/cloud/sdk/core/http/InputStreamRequestBody.java

I'm trying to take a look at [this issue](https://github.com/watson-developer-cloud/java-sdk/issues/1094) I got in the public Watson SDK. Basically, a user is seeing `OutOfMemory` errors when trying to send a large number of audio files. I haven't been able to replicate the issue.
They're claiming that this wasn't the case with v7.3.0 of the Java SDK. From a generated service perspective, I didn't see anything that might've been the culprit. I turned to the change in core version being used, which was v4.5.0 -> v7.0.0, to try and find the issue. You can see a diff of those versions here: https://github.com/IBM/java-sdk-core/compare/4.5.0...7.0.0
Looking through that I still didn't really see any issues. This change that I made was one thing that stood out to me as a possible memory leak. …

Close extra stream used to save byte array in InputStreamRequestBody

---

src/main/java/com/ibm/cloud/sdk/core/security/AbstractToken.java
src/main/java/com/ibm/cloud/sdk/core/security/CloudPakForDataAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/Cp4dToken.java
src/main/java/com/ibm/cloud/sdk/core/security/IamAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/IamToken.java
src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/test/BaseServiceUnitTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1261
This PR will propagate an exception that occurs on the thread where the token service invocation is made... back to the main request thread where the authenticator's authenticate() method is being invoked.

fix: propagate token server exception to main request invocation thread

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java

Fixes the case when a list formatted object is passed to the request builder. Now, this is converted to a string then passed to the content builder.

fix: use correct json serialization for lists

---

src/main/java/com/ibm/cloud/sdk/core/util/DateDeserializer.java
src/test/java/com/ibm/cloud/sdk/core/util/DateDeserializerTest.java

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1512
This PR adds an additional formatter to the DateDeserializer class to handle date values of the form "yyyy-MM-dd".

fix: add support for deserializing RFC3339 full-date values

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
src/test/resources/my-credentials.env
src/test/resources/vcap_services.json

ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1738, https://github.ibm.com/arf/planning-sdk-squad/issues/1742
Changes/fixes:
- Empty path segments `""` are no longer added to the request url to prevent the java request url builder library from adding a `/` in place of the empty path segment
- When parsing a credentials file (vcap or environment file), the credential's key/value pairs are trimmed of whitespace

fix: trailing slash in request url & remove whitespace when parsing external config properties

---

src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
src/test/resources/my-credentials.env
src/test/resources/vcap_services.json

ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1759
Changes:
- allow for a env config property's value to contain the ``=`` character
- add unit test cases

fix: allow '=' character in environment config values

---

src/main/java/com/ibm/cloud/sdk/core/service/model/DynamicModel.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java

This PR adds a setter for the dynamic properties of a DynamicModel -- a model with "additionalProperties". 
Tests are included.

Add setter for properties of DynamicModel

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java

Fixes arf/planning-sdk-squad#901
The RequestBuilder.bodyContent() method is modified to no
longer use the contentType parameter to determine which one of the
other three input parameters should be used to create the request body.
Instead, we now use the first non-null value using the order
'jsonContent', 'jsonPatchContent', then 'nonJsonContent'.
This change is necessary for us to implement the JSON streaming
feature, where the SDK user might serialize the JSON content
himself and pass it in as a String or InputStream while also
using a contentType that would otherwise indicate a JSON body.

feat: RequestBuilder changes to support JSON streaming feature

---

src/main/java/com/ibm/cloud/sdk/core/util/DynamicModelTypeAdapterFactory.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java

This PR introduces a change to the DynamicModelTypeAdapterFactory that will allow null values found in dynamic properties to be explicitly serialized into a JSON string.

Explicitly serialize null dynamic property values

---

src/main/java/com/ibm/cloud/sdk/core/util/DiscriminatorBasedTypeAdapterFactory.java
src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DiscriminatorSerializationTest.java

Fixes arf/planning-sdk-squad#2011
We initially did not implement the "write()" method within the
DiscriminatorBasedTypeAdapterFactory because we should never
encounter an actual instance of a discriminated base class
(they are implemented as abstract base classes).
However, in some scenarios Gson will use a type adapter
that reflects the DECLARED type rather than the actual RUNTIME type
associated with an object.  One such scenario is when a class
contains a field which is defined as a List of some type X, where
X is a discriminated base class (oneOf parent).
For this reason, it's possible that the write() method is
called.  This commit implements the write() method so that it
simply delegates to the TypeAdapter associated with the
object's RUNTIME type.

fix: support serialization of models containing lists of discriminated subclasses

---

src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java

This PR will allow ServiceResponseErrors to be returned directly, as opposed to in the `causedBy:` of a RuntimeException.

fix: surface ServiceResponseError outside of RuntimeError

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java

This commit adds method resolveRequestURL to the RequestBuilder class
as a replacement for the constructHttpUrl() method.

feat: add method RequestBuilder.resolveRequestUrl

---

src/main/java/com/ibm/cloud/sdk/core/security/Cp4dToken.java
src/main/java/com/ibm/cloud/sdk/core/security/IamToken.java

Similar to https://github.com/IBM/go-sdk-core/pull/73, this PR simply fixes the flaw in the token refresh logic described in https://github.ibm.com/arf/planning-sdk-squad/issues/2149 by updating the new ``refreshTime`` calculation to be 1 minute ahead of the current time vs 1 minute ahead of the previous ``refreshTime`` value.

fix: iam/cp4d token refresh logic

---

src/main/java/com/ibm/cloud/sdk/core/security/Authenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/IamAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
src/test/resources/my-credentials.env

The IAM /identity/token (get token) operation supports an optional "scope" form parameter which can be used to obtain an IAM access token having a limited set of scopes in this it can be used.
This commit adds support for the "Scope" field within the IamAuthenticator class. If set, the value of this field is sent as the "scope" form param in the "get token" request body when obtaining an access token.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2167

feat(IAM Authenticator): add support for optional 'scope' property

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java
src/main/java/com/ibm/cloud/sdk/core/http/HttpConfigOptions.java
src/main/java/com/ibm/cloud/sdk/core/http/gzip/GzipRequestInterceptor.java
src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/http/HttpConfigTest.java
src/test/java/com/ibm/cloud/sdk/core/test/http/gzip/GzipTest.java
src/test/java/com/ibm/cloud/sdk/core/test/http/ratelimit/RateLimitTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/BaseServiceTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ConfigureServiceTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestTest.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
src/test/resources/my-credentials.env

This PR adds support for compressing request bodies using gzip. A new ``enableGzipCompression`` method was added as part of the BaseService class, and is used to add the ``GzipRequestInterceptor`` to the instance of the Base Service's http client. This new interceptor sets the ``Content-Encoding`` of the request body to ``gzip``, if no ``Content-Encoding`` header exists and then compresses the request body.
**The version of okhttp was also upgraded to v4.9.0**
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2181

feat: add support for gzip request body compression and upgrade okhttp version

---

pom.xml

This PR upgrades the `commons-codec` dependency to `1.13` to address a vulnerability discovered by Snyk.

chore: upgrade common-codec dependency

---

src/main/java/com/ibm/cloud/sdk/core/util/DateDeserializer.java
src/main/java/com/ibm/cloud/sdk/core/util/DateUtils.java
src/main/java/com/ibm/cloud/sdk/core/util/OpenAPIDateSerializer.java
src/main/java/com/ibm/cloud/sdk/core/util/OpenAPIDateTimeSerializer.java
src/test/java/com/ibm/cloud/sdk/core/util/DateDeserializerTest.java
src/test/java/com/ibm/cloud/sdk/core/util/DateUtilsTest.java

Fixes arf/planning-sdk-squad#2289
This commit introduces a new class (DateUtils) which will
be used by the Java generator to properly format date and date-time
values when they are used as query parameters.

feat: add new DateUtils utility class

---

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/InvalidServiceResponseException.java
src/main/java/com/ibm/cloud/sdk/core/service/exception/ServiceResponseException.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

This commit introduces a new InvalidServiceResponseException class,
which will wrap any exception caught while processing the response
received from the server for an otherwise successful operation
invocation.  For example, an exception thrown by GSON due to a
JSON unmarshalling error will now be wrapped in an
InvalidServiceResponseException (a subclass of ServiceResponseException).

feat: wrap exceptions during client-side response processing

---

.gitignore
Authentication.md
src/main/java/com/ibm/cloud/sdk/core/security/AuthenticatorBase.java
src/main/java/com/ibm/cloud/sdk/core/security/BasicAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/BearerTokenAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/CloudPakForDataAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/ConfigBasedAuthenticatorFactory.java
src/main/java/com/ibm/cloud/sdk/core/security/Cp4dToken.java
src/main/java/com/ibm/cloud/sdk/core/security/Cp4dTokenResponse.java
src/main/java/com/ibm/cloud/sdk/core/security/IamAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BasicAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BearerTokenAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorLiveTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorLiveTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
src/test/resources/cp4d_token.json
src/test/resources/refreshed_cp4d_token.json

The main focus of this change is to enhance the CloudPakForDataAuthentictor
implementation to support the official "POST /v1/authorize" operation for
obtaining an access token.   This includes support for using either a password
or an apikey when obtaining the access token from the token service.
In addition, a new Builder class was introduced which provides a more user-friendly
way to construct instances of CloudPakForDataAuthenticator.  The "fromConfiguration"
method was also added to replace the (now deprecated) map-based ctor.
In order to keep the IamAuthenticator class in sync with CloudPakForDataAuthenticator,
the Builder class and fromConfiguration() method were also added to IamAuthenticator.
In the case of both authenticators, the existing set of constructors are still supported …

feat(authentication): support cp4d /v1/authorize operation

---

src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorLiveTest.java

This PR updates the IAM live server test to fix the comments that described the required config properties, plus it adds a test that verifies that a refresh token can be obtained using the authenticator.

test: fix iam live test

---

src/main/java/com/ibm/cloud/sdk/core/util/UrlHelper.java
src/test/java/com/ibm/cloud/sdk/core/util/UrlHelperTest.java

This PR adds a small utility method to extract the value of a query parameter from a URL string. This will be used in the pagination support for Java.

Add getQueryParam utility method to support pagination

---

src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

This PR contains a few new test cases involving empty or missing operation responses.  This was mainly done to confirm the behavior of the Java core (and by extension Gson) in these situations.

test: adds tests re: missing/empty empty operation responses

---

pom.xml

This PR upgrades our okhttp3 dependency to the latest stable version (4.9.1).

build: upgrade okhttp3 dependency to v4.9.1

---

src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorLiveTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/HeadersTest.java

This commit adds tests to verify that the "Host" request
header can be explicitly set in the following ways:
- As part of a service request (request builder)
- As a custom header while constructing an IAM Authenticator instance
- As a custom header while constructing a CP4D Authenticator instance

test: add tests involving Host header

---

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ParameterizedUrlTest.java

This is consistent with the naming convention of `setServiceUrl`.

fix: change method name to `constructServiceUrl`

---

pom.xml

This PR increases the `source` and `target` version of maven-compiler-plugin to `1.8`.
The whole platform SDK test set was executed on my local machine using a snapshot build, including this change, from the core and all tests passed.

fix: bump maven-compiler-plugin source and target version to 1.8

---

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/service/BaseServiceTest.java

Remove the `final` modifier from the `BaseService#createServiceCall` to allow extending services to override.
This provides a hook point that can be used to modify every request earlier than an interceptor is able to do so.
Added a test that will fail to compile if the final modifier is re-added inadvertently. The assertion itself is slightly pointless as it effectively validates the JVM's override functionality, but it seems nicer than having a "compile-only" test.
Note also as per [JLS 13.4.17](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.17) is a binary compatible change.

feat(BaseService): remove final modifier from createServiceCall

---

src/test/java/com/ibm/cloud/sdk/core/util/LongToDateTimeAdapterTest.java

This Pr brings 100% coverage for the `LongToDateTypeAdapter`. This adapter is not used in the Gson setup the core provides by default, but part of the core and has to be covered by tests.
The overall coverage looks like below.
Note the following:
- I went a little bit further than 100% coverage and created a few extra tests simulating real world cases
- cases where deprecated constructors of Date class used, like `new Date(1990, 1, 1)` aren't covered
- there is a discrepancy of how the case is managed when empty string the value in the json string ( `{date:""}`, this adapter throws exception, but the `BooleanToStringTypeAdapter` handles it as `NULL` value. I provided a test covering this for documentation pusposes and created a ticket on our board about to check consistency across …

test: unit tests covering LongToDateTypeAdapter

---

.secrets.baseline
src/test/java/com/ibm/cloud/sdk/core/test/service/ResponseTest.java

This PR brings unit test improvements for `ResponseConverterUtils` and `ResponseUtils` classes.
**Notes**:
- I took the liberty refactoring the tests into AAA format (without changing what and how they do), and moving the input parameters into the tests, renaming the methods and removing documentation headers. As the volume of test cases grew it was difficult to scroll back and fort between the method and the input values placed on the top of the file.
- I also renamed the methods of the test service so they tells more about which underlying `ResponseConverterUtils` method is called
- I extended the already implemented positive test cases with negative tests for having some coverage on corner cases
- there are seemingly superflous test cases, I added these to document the existing …

tests: improve test coverage responseconverterutils

---

src/main/java/com/ibm/cloud/sdk/core/http/gzip/GzipRequestInterceptor.java
src/test/java/com/ibm/cloud/sdk/core/test/http/gzip/GzipTest.java

There is no value in compressing something of zero-length and this helps resolve a quirky problem.
OkHttp appears to [send `DELETE` requests](https://github.com/square/okhttp/issues/654) with a zero length (as opposed to `null` body). Since the compressed length is not known in advance a compressed zero length body is sent chunked, which requires the receiving server to read the [non-existent] body (as it doesn't know it is empty). Some servers don't expect a body on `DELETE` requests (because the spec is ambiguous on the matter) and then fail to handle the `DELETE` request. If the body isn't compressed we avoid this bad path.
Added a test that verfies the compression is bypassed for a `DELETE` request with zero length.

fix(http): avoid gzipping zero length content

---

src/main/java/com/ibm/cloud/sdk/core/security/IamAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/IamRequestBasedAuthenticator.java

This commit introduces the IamRequestBasedAuthenticator class
which will serve as a common base class for any authenticator
impl that interacts with the IAM token service to obtain an
access token.
Common code was moved from the IamAuthenticator class to
the new IamRequestBasedAuthenticator base class.

refactor: prepare for ContainerAuthenticator impl

---

src/main/java/com/ibm/cloud/sdk/core/security/ContainerAuthenticator.java

This PR fixes a few javadoc comment-related issues in the ContainerAuthenticator class I noticed while working on the new VpcInstanceAuthenticator.

fix(ContainerAuthenticator): fix some javadoc comments

---

.travis.yml

This PR updates the build to use node 14 to satisfy semrel's new release.
I also tweaked our use of python to use python3 with bump2version as well

chore(build): fix semrel build step

---

build/setupSigning.sh

This PR fixes the gpg import step for the "bionic" travis image.   This is needed due to the fact that "bionic" uses a more recent version of the "gpg" command.

chore(build): fix gpg import

---

pom.xml

This PR fixes the gpg signing step on the travis bionic image, which has a newer version of the gnupg (gpg) command.

fix(build): fix gpg signing step on travis bionic image

---

.secrets.baseline
src/main/java/com/ibm/cloud/sdk/core/security/BasicAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/BearerTokenAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/test/BaseServiceUnitTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BasicAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BearerTokenAuthenticatorTest.java

When `authenticate` method called by `BasicAuthenticator`, `BearerTokenAuthenticator` or `TokenRequestBasedAuthenticator` second time on the same request it adds second `Authorization` header to the request. This can lead to a consecutive failure with `400` error from the services with strict rules about headers' double entries.
This PR switches named authenticators to use `builder.header` method to prevent that.

fix: Prevent double entries of Authorization header on second authenticate call

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java

This commit addresses a gson-related security vulnerability by upgrading our gson dependency to version 2.8.9 (the current latest).

fix: bump gson dependency to 2.8.9

---

src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java

When the java core was recently upgraded to gson version 2.8.9,
that included a change to set gson's "objectToNumber"
policy to be "LAZILY_PARSED_NUMBER", but that was incorrect.
It should be set to "DOUBLE".
This commit makes this change, which means that if a JSON string
is unmarshalled into a generic Map<String, Object>, then any
JSON "number" values that are encountered will now be unmarshalled
into a Double instead of a LazilyParsedNumber.
This change restores the behavior seen in gson versions prior to
2.8.9 (and java core versions prior to 9.13.4).

fix: set gson's objectToNumber policy to DOUBLE

---

.cra/.cveignore
pom.xml

Logback core module recently added a `1.2.7` version that fixes an existing vulnerability. This updates to that new version.

fix: update logback version to fix vulnerability

---

pom.xml

This PR removes the dependency for logback-classic (which in turn pulled in logback-core).
Because the java core code uses the java.util.logging interface, there is no need for logback at all.

fix: remove unnecessary logback dependency

---

.travis.yml

This commit removes the "type = push" criteria from the semrel build stage so that we can manually trigger a build of the main branch and also cause the semrel stage to fire.   This was needed because for a manually triggered build, the build type is "api" and not "push".

build: refine criteria for semrel build stage

---

src/main/java/com/ibm/cloud/sdk/core/security/ConfigBasedAuthenticatorFactory.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BasicAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/ConfigBasedAuthenticatorFactoryTest.java

This commit changes the visibility of the
"ConfigBasedAuthenticatorFactory.createAuthenticator()" method from
private to protected to allow SDKs to override this class
in order to support alternate configuration sources
(e.g. injected spring properties).

fix: set visibility of ConfigBasedAuthenticatorFactory.createAuthenticator to protected

---

.cra/.cveignore

This PR adds a .cveignore file entry for the kotlin-stdlib vulnerability which is a false positive.

chore: ignore kotlin-stdlib vuln false positive

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/util/DynamicModelTypeAdapterFactory.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelTest.java

This PR bumps our gson dependency to the current latest (2.9.0).
Included in this are changes to wean us off the GSON ReflectionAccessor class, which is no longer present in v2.9.0.

fix: bump gson to 2.9.0

---

.secrets.baseline
src/main/java/com/ibm/cloud/sdk/core/http/DefaultRetryStrategy.java
src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java
src/main/java/com/ibm/cloud/sdk/core/http/IRetryInterceptor.java
src/main/java/com/ibm/cloud/sdk/core/http/IRetryStrategy.java
src/main/java/com/ibm/cloud/sdk/core/http/RetryInterceptor.java
src/test/java/com/ibm/cloud/sdk/core/test/http/HttpClientSingletonTest.java
src/test/java/com/ibm/cloud/sdk/core/test/http/retry/RetryTest.java

This commit provides a pluggable way for users of the java core
to supply their own retry interceptor implementation in order
to customize the conditions under which retries are automatically
attempted.
Included in these changes is the notion of a "retry strategy",
which is a factory for creating retry interceptor instances.
Users of the java core (e.g. an SDK project) can implement
their own retry strategy and then set it with the
HttpClientSingleton.setRetryStrategy() static method.
Once set, the registered factory's createRetryInterceptor()
method will be called whenever the java core needs to initialize an
http client instance when retries are enabled.
The factory's createRetryInterceptor() method returns an implementation
of the IRetryInterceptor interface (which is itself a subclass …

feat: support user-defined retry interceptors

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/security/AbstractToken.java

This commit includes a small change to the AbstractToken
class to avoid an InaccessibleObjectException when
running code using a Java 17 JRE.
In addition, the pom.xml was updated to make it easy
to build/test with a Java 17 JDK... just add "-P java17"
to the mvn command line.
Note: although we don't yet include a java17-based build in Travis, I've tested locally and with the changes in this PR, I'm able to build and test the project cleanly by running `mvn clean install -P java17` while using the Oracle Java 17 JDK.
Unfortunately, I have to use the `--add-opens` JVM option when running unit tests due to InaccessibleObjectException's that
occur in some of our dependencies (mostly powermock, etc.).

fix: allow java16+ as JRE

---

.travis.yml

This PR adds a build stage to the travis build config that will build & test the project using java 17 (openjdk17)

build: add travis stage for java 17

---

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java
src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/test/java/com/ibm/cloud/sdk/core/security/VpcInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/http/HttpClientSingletonTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/ContainerAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java

This commit modifies the java core so that users can now
specify a fully-configured OkHttpClient instance to be
used by service and authenticator instances:
1. The HttpClientSingleton class now has methods setHttpClient()
and getHttpClient().  These methods can be used to set and get
the default client configuration from which other OkHttpClient
instances are created.
2. The TokenRequestBasedAuthenticator base class now has methods
setClient() and getClient().  These methods can be used to set
and get the specific OkHttpClient instance that should be used
by an authenticator when interacting with the token service.
These new methods are inherited by each of the request-based
authenticator implementation classes: ContainerAuthenticator,
CloudPakForDataAuthenticator, …

feat: allow user-specified default OkHttpClient instance

---

pom.xml

fix: Update okhttp dependency to address CVE-2021-0341

---

.cra/.cveignore

While running the cra ad-hoc report job against the java core, the resulting report stated:
So, this PR removes that entry from .cra/.cveignore.

build: remove unnecessary cve from .cveignore

---

src/main/java/com/ibm/cloud/sdk/core/util/GsonSingleton.java
src/test/java/com/ibm/cloud/sdk/core/util/GsonSingletonTest.java

This commit makes a small change to our Gson factory so that it sets the "object to number" strategy to LAZILY_PARSED_NUMBER. The default value (DOUBLE) does not provide the fidelity needed when performing marshalling/unmarshalling steps involving generic datastructures like Map<String,Object>.

fix: use gson 'lazily parsed number' for 'object to number' strategy

---

pom.xml
src/test/java/com/ibm/cloud/sdk/core/security/VpcInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/BaseServiceUnitTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/ConfigBasedAuthenticatorFactoryTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/ContainerAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java

This commit modifies the project so that the mockito library is used for mocking within testcases instead of powermock.

test: transition from powermock to mockito for testing

---

.cra/.cveignore
.secrets.baseline
.travis.yml
CONTRIBUTING.md
pom.xml
src/test/java/com/ibm/cloud/sdk/core/test/http/ratelimit/RateLimitTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceInstanceAuthenticatorLiveTest.java

This commit modifies the project so that we now require java 11 for build/test.  We still produce java8-compatible classes, but we require java 11+ for building/testing due to dependency requirements.

build: java 11 min jdk for build/test

---

pom.xml
src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/main/java/com/ibm/cloud/sdk/core/security/AuthenticatorBase.java
src/main/java/com/ibm/cloud/sdk/core/security/JsonWebToken.java
src/test/java/com/ibm/cloud/sdk/core/test/http/HttpConfigTest.java
src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/BasicAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/util/RequestUtilsTest.java

The guava dependency is large and causes [CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908) to get flagged by some scanning tools (though to be clear the vulnerable guava method is not used in this code).
Since guava is used in just a few places it could be removed to reduce the size of the SDKs and prevent this false positive vulnerability warning.
This PR:
* Removes `guava-version` and the guava dependency block from the pom
* Updates `RequestBuilder` to use okhttp's path segment encoding instead of guava's URL escaper
* Replaces guava base64 encoding/decoding with `java.util.Base64`
* Replaces some list/set initialization in test classes.
* Finally, removes `javax.annotation.Nullable` (as supplied by the guava package) that was referenced by `HttpConfigTest`

refactor: remove guava dependency

---

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
src/test/java/com/ibm/cloud/sdk/core/test/service/BaseServiceTest.java

The RFC for content-type header format allows optional whitespace before the semicolon. Our regular expressions for recognizing various mime types do not account for this, so valid mime types may not be recognized. This commit adjusts the expression to close that gap.

fix: recognize content types with whitespace

---

pom.xml

This PR bumps our dependency on the okhttp library to the most recent 4.x release (4.11.0).

feat: bump okhttp to 4.11.0

---

Authentication.md
src/main/java/com/ibm/cloud/sdk/core/security/ContainerAuthenticator.java

This commit adds support for a second default CR token filename. If the user doesn't specify a CR token filename, the authenticator will first try '/var/run/secrets/tokens/vault-token', and then '/var/run/secrets/tokens/sa-token' in that order.

fix(ContainerAuthenticator): add sa-token as default CR token filename

---

build/generateJavadocIndex.sh
build/publishJavadoc.sh

These changes are needed because Github Pages no longer supports the use of symlinks unless one is using a paid account.

build: fix javadoc-related scripts

---

src/main/java/com/ibm/cloud/sdk/core/http/RequestBuilder.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestBuilderTest.java
src/test/java/com/ibm/cloud/sdk/core/test/service/RequestTest.java

This PR fixes RequestBuilder.resolveRequestUrl() so that it will retain a trailing slash found on an operation path when adding the path segments to form the request URL.

fix(RequestBuilder): retain trailing slash on operation path

---

build/publishJavadoc.sh

This commit modifies the publishJavadoc.sh script
to remove the creation of the "latest" symbolic
link.  This is being done because github no longer allows us to include symbolic links in the gh-pages branch.

build: remove 'latest' link from gh-pages

---

pom.xml

The maven warnings were just bugging me :)

build: remove obsolete jacoco config

---

pom.xml

Upgrade okhttp to 4.12.0.
Revert the okio version override since 4.12.0 has a newer dependency.

Upgrade okhttp 4.12.0

---

.secrets.baseline
src/main/java/com/ibm/cloud/sdk/core/service/exception/ServiceResponseException.java
src/test/java/com/ibm/cloud/sdk/core/test/service/ErrorResponseTest.java

This commit adds the "getResponseBody" method to the ServiceResponseException class (which serves as a baseclass for all our exceptions).  This new method can be used to retrieve the entire response body that was received within an error response from a server.
Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/3841

feat(ServiceResponseException): added getResponseBody() method

---

src/main/java/com/ibm/cloud/sdk/core/security/CloudPakForDataAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/CloudPakForDataServiceAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/CloudPakForDataServiceInstanceAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/ContainerAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/IamAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/MCSPAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/TokenRequestBasedAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/security/VpcInstanceAuthenticator.java
src/main/java/com/ibm/cloud/sdk/core/util/RequestUtils.java
src/test/java/com/ibm/cloud/sdk/core/security/VpcInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/ContainerAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/Cp4dServiceInstanceAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/test/security/MCSPAuthenticatorTest.java
src/test/java/com/ibm/cloud/sdk/core/util/RequestUtilsTest.java

This commit updates our various request-based authenticators so that the User-Agent header is included with each outbound token request. The value of the User-Agent header will be of the form "ibm-java-sdk-core/<authenticator-type>-<core-version> <os-info>".

feat: send user-agent header with auth token requests

---

Authentication.md
src/main/java/com/ibm/cloud/sdk/core/security/ContainerAuthenticator.java

This pull request extends the existing ContainerAuthenticator to be aware of the hard-coded compute resource token path used by Code Engine. This allows a seamless usage of that authenticator and a move of workload between IKS/ROKS/Code Engine without changing a single line of code.
Documentation is adjusted to mention Code Engine in the context of the ContainerAuthenticator.

feat(ContainerAuthenticator): enhance ContainerAuthenticator to support Code Engine workload

---

.secrets.baseline

This detect-secrets violation occurs due to the change that was made to CHANGELOG.md.  Just updated .secrets.baseline to suppress it.

fix(build): mark secret as false positive

---

pom.xml

Bumps dependencies to their newest version. Gson to 2.13.1, mockito to 5.18.0

fix(build): bump dependencies
