.travis.yml, build/bintray-config.template
Of course, I missed one little spot in the .travis.yml script that needed to be changed :)
=> Fix post-deploy step in travis build

.travis.yml, build/bintray-config.template
Hopefully a final tweak to the deployment part of the build :)
=> Fixed deployment config

src/test/java/com/ibm/cloud/sdk/core/test/util/RequestUtilsTest.java
This PR just fixes a test I wrote where I was always looking for the default version, which doesn't make sense on tagged commits 🙃
=> Fix failing unit test

src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java, src/test/resources/vcap_services.json
This pull request refactors bluemix to cloud.ibm.
=> Refactor bluemix to cloud.ibm

.pre-commit-config.yaml, .secrets.baseline
This PR adds the detect secrets pre-commit hook to help prevent leaking of things like secret keys.
=> Add detect secrets

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java, src/main/java/com/ibm/cloud/sdk/core/http/HttpConfigOptions.java, src/test/java/com/ibm/cloud/sdk/core/test/http/HttpConfigTest.java
This PR fixes issue #44. @lpatino10
=> Allow for authentication for configured proxy

src/main/java/com/ibm/cloud/sdk/core/service/model/FileWithMetadata.java, src/test/java/com/ibm/cloud/sdk/core/test/model/FileWithMetadataTest.java
This PR adds the "FileWithMetadata" class to the "models" package of the core for use as the item value in an array of files parameter.
=> New FileWithMetadata class to support arrays of files in form data

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
Updating the error message that comes with an `SSLHandshakeException` along with the rest of the rest of the SDKs.
=> Update error message for SSLHandshakeException

src/main/java/com/ibm/cloud/sdk/core/util/RequestUtils.java
Fixes: https://github.com/IBM/java-sdk-core/issues/58
=> fix: make sure stream is closed after loading properties file

README.md
See https://github.ibm.com/arf/planning-sdk-squad/issues/1133
=> Add Java minimum version

src/main/java/com/ibm/cloud/sdk/core/util/CredentialUtils.java, src/test/java/com/ibm/cloud/sdk/core/test/security/ConfigBasedAuthenticatorFactoryTest.java, src/test/java/com/ibm/cloud/sdk/core/test/service/ConfigureServiceTest.java, src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1762
Changes:
- Support java system properties as an alternative to environment variables for config properties
- Add unit tests
=> feat: support service configuration via system properties

.travis.yml, README.md, pom.xml
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1957
=> BREAKING CHANGE: upgrade okhttp3 dependency to 3.14.9

src/main/java/com/ibm/cloud/sdk/core/util/DynamicModelTypeAdapterFactory.java, src/test/java/com/ibm/cloud/sdk/core/test/model/DynamicModelSerializationTest.java
Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/2059
This commit improves the behavior of the DynamicModelTypeAdapterFactory's
serialization function so that we support the serialization of null values
found within additional properties in a more accurate way.
1. A null-valued additional property will be serialized as null in the JSON.
2. A null-valued normal property that is set as an additional property
will NOT be serialized as a null.
3. The above "serialize nulls" behavior also applies to additional property
values which are model instances.
=> fix: improve serialize-nulls in additional properties

.travis.yml, CONTRIBUTING.md, README.md, build/publishCodeCoverage.sh, build/publishJavadoc.sh, pom.xml
This PR upgrades automation and documentation to use the new `main` branch.
=> fix(build): main migration

build/checkstyle.xml, pom.xml, src/main/java/com/ibm/cloud/sdk/core/util/UrlHelper.java
Updates the guava dependency to avoid vulnerabilities, plus a few other deps.
Oh, and I also fixed a few javadoc warnings.
=> fix(deps): update dependencies to avoid vulnerabilities

src/main/java/com/ibm/cloud/sdk/core/http/HttpClientSingleton.java, src/main/java/com/ibm/cloud/sdk/core/http/HttpConfigOptions.java, src/main/java/com/ibm/cloud/sdk/core/http/RetryInterceptor.java, src/main/java/com/ibm/cloud/sdk/core/http/ratelimit/RateLimitConstants.java, src/main/java/com/ibm/cloud/sdk/core/http/ratelimit/RateLimitContext.java, src/main/java/com/ibm/cloud/sdk/core/http/ratelimit/RateLimitInterceptor.java, src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java, src/main/java/com/ibm/cloud/sdk/core/util/DateUtils.java, src/test/java/com/ibm/cloud/sdk/core/test/http/ratelimit/RateLimitTest.java, src/test/java/com/ibm/cloud/sdk/core/test/http/retry/RetryTest.java, src/test/java/com/ibm/cloud/sdk/core/util/CredentialUtilsTest.java, src/test/java/com/ibm/cloud/sdk/core/util/DateUtilsTest.java, src/test/resources/my-credentials.env
This PR improves the HTTP retry support to match with the functionality of the other SDK cores.
=> feat: improve retry functionality

src/test/java/com/ibm/cloud/sdk/core/test/security/ContainerAuthenticatorTest.java, src/test/java/com/ibm/cloud/sdk/core/test/security/IamAuthenticatorTest.java
This PR just adds some debug logging capabilities to the ContainerAuthenticatorTest and IamAuthenticatorTest classes
=> test: add debug logging to auth tests

src/main/java/com/ibm/cloud/sdk/core/http/RetryInterceptor.java
This commit adds an extra status code check to the `shouldRetry` method.
=> chore: improve retry conditions

pom.xml
=> build: bump dependency versions

.secrets.baseline, pom.xml
This PR bumps our verison of gson to the latest available.
=> build: bump gson version

Authentication.md
=> docs: add VPC-related note to auth docs

.travis.yml
=> build: tweak pyenv command

src/main/java/com/ibm/cloud/sdk/core/service/BaseService.java
This huge change was just intended to make the various cores consistent :)
=> fix: tweak JSON parsing error message

pom.xml
=> fix: bump okio transitive dependency to avoid CVE

.secrets.baseline, pom.xml
=> fix: bump dependencies to avoid vulnerabilities
